"""added password_hash column

Revision ID: 34034ddec67a
Revises: baedd9c4d800
Create Date: 2025-09-26 19:15:23.037911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34034ddec67a'
down_revision = 'baedd9c4d800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
